// Catálogo Ypê — 185 SKUs reais + imagens oficiais ype.ind.br
// 87/185 produtos com imagem oficial Ypê
window.YPE_PRODUCTS = [
 {
  "id": "YPE-0003",
  "name": "Alvejante Ypê (sem cloro)",
  "category": "Lavanderia",
  "family": "Alvejante",
  "brand": "Ypê",
  "package": "1 L",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0003",
  "desc": "Ypê · Alvejante · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0004",
  "name": "Amaciante Concentrado Ypê Frescor das Flores",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amaciante-conc-1l-encanto-das-flores.png",
  "link": "ype-0004",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0005",
  "name": "Amaciante Concentrado Ypê Romance da Primavera",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0005",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0006",
  "name": "Amaciante Concentrado Ypê Coco e Baunilha",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amaciante_conc_coco-e-baunilha.png",
  "link": "ype-0006",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0007",
  "name": "Amaciante Concentrado Ypê Delicado",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0007",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0008",
  "name": "Amaciante Concentrado Ypê Essencial",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0008",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0009",
  "name": "Amaciante Concentrado Ypê Encanto das Flores",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amaciante-conc-1l-encanto-das-flores.png",
  "link": "ype-0009",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0010",
  "name": "Amaciante Concentrado Ypê Alquimia Inspiração",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 10.84,
  "listPrice": 13.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0010",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0011",
  "name": "Amaciante Concentrado Ypê por L'Occitane Perfume Fresco",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 13.18,
  "listPrice": 16.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0011",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0012",
  "name": "Amaciante Concentrado Ypê por L'Occitane Perfume Sofisticado",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 13.18,
  "listPrice": 16.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0012",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0013",
  "name": "Amaciante Concentrado Ypê Brisa Lilás",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amaciante-conc-1l-brisa-lilas.png",
  "link": "ype-0013",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0014",
  "name": "Amaciante Concentrado Ypê Green",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 10.84,
  "listPrice": 13.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_green_amaciante-concentrado-1l.png",
  "link": "ype-0014",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0015",
  "name": "Amaciante Concentrado Ypê Antibac",
  "category": "Lavanderia",
  "family": "Amaciante Concentrado",
  "brand": "Ypê",
  "package": "1 L",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_antibac-amaciante-concentrado-1l.png",
  "link": "ype-0015",
  "desc": "Ypê · Amaciante Concentrado · 1 L · 12 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0016",
  "name": "Amaciante Ypê Tradicional Aconchego Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0016",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0017",
  "name": "Amaciante Ypê Tradicional Primavera Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0017",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0018",
  "name": "Amaciante Ypê Tradicional Delicado Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0018",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0019",
  "name": "Amaciante Ypê Tradicional Frescor das Flores Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amaciante-conc-1l-encanto-das-flores.png",
  "link": "ype-0019",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0020",
  "name": "Amaciante Ypê Tradicional Intenso Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0020",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0021",
  "name": "Amaciante Ypê Pro Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Ypê",
  "package": "2 L",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0021",
  "desc": "Ypê · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0022",
  "name": "Amaciante Atol Jardim Perfumado",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Atol",
  "package": "2 L",
  "price": 6.16,
  "listPrice": 7.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0022",
  "desc": "Atol · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0023",
  "name": "Amaciante Atol Jardim Perfumado Ultra",
  "category": "Lavanderia",
  "family": "Amaciante Tradicional",
  "brand": "Atol",
  "package": "2 L",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0023",
  "desc": "Atol · Amaciante Tradicional · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0080",
  "name": "Sabão em Barra Ypê Green",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-green.png",
  "link": "ype-0080",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0081",
  "name": "Sabão em Barra Ypê Neutro",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-neutro-rosa.png",
  "link": "ype-0081",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0082",
  "name": "Sabão em Barra Ypê Multiativo",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0082",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0083",
  "name": "Sabão em Barra Ypê Fresh",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-fresh-verde-claro.png",
  "link": "ype-0083",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0084",
  "name": "Sabão em Barra Ypê Aloe Vera",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-aloe-vera-verde-1745344589.png",
  "link": "ype-0084",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0085",
  "name": "Sabão em Barra Ypê Coco e Toque de Aveia",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0085",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0086",
  "name": "Sabão em Barra Ypê Flores e Frutas com Lavanda",
  "category": "Lavanderia",
  "family": "Sabão em Barra",
  "brand": "Ypê",
  "package": "5x200g (1kg)",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-fresia-e-pessego.png",
  "link": "ype-0086",
  "desc": "Ypê · Sabão em Barra · 5x200g (1kg) · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0087",
  "name": "Sabão em Pasta Assolan",
  "category": "Lavanderia",
  "family": "Sabão em Pasta",
  "brand": "Assolan",
  "package": "500 g",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_assolan-sabao-em-pasta-1724171941.png",
  "link": "ype-0087",
  "desc": "Assolan · Sabão em Pasta · 500 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0088",
  "name": "Sabão em Pasta Atol",
  "category": "Lavanderia",
  "family": "Sabão em Pasta",
  "brand": "Atol",
  "package": "500 g",
  "price": 3.89,
  "listPrice": 4.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_atol-sabao-em-pasta-atol-1727787622.png",
  "link": "ype-0088",
  "desc": "Atol · Sabão em Pasta · 500 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0089",
  "name": "Lava Roupas em Pó Ypê Power Act",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Ypê",
  "package": "1 kg",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0089",
  "desc": "Ypê · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0090",
  "name": "Lava Roupas em Pó Ypê Power Act Sachê",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Ypê",
  "package": "800 g",
  "price": 6.62,
  "listPrice": 8.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0090",
  "desc": "Ypê · Sabão em Pó · 800 g · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0091",
  "name": "Lava Roupas em Pó Tixan Maciez Sachê",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "800 g",
  "price": 6.62,
  "listPrice": 8.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0091",
  "desc": "Tixan · Sabão em Pó · 800 g · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0092",
  "name": "Lava Roupas em Pó Tixan Power Act",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 7.40,
  "listPrice": 9.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0092",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0093",
  "name": "Lava Roupas em Pó Tixan Power Act Sachê",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "800 g",
  "price": 6.62,
  "listPrice": 8.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0093",
  "desc": "Tixan · Sabão em Pó · 800 g · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0094",
  "name": "Lava Roupas em Pó Tixan Primavera",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 6.62,
  "listPrice": 8.49,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0094",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0095",
  "name": "Lava Roupas em Pó Tixan Ypê Antibac Sachê",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "800 g",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_antibac-lrp-tixan-sache-800g.png",
  "link": "ype-0095",
  "desc": "Tixan · Sabão em Pó · 800 g · 20 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0096",
  "name": "Lava Roupas em Pó Tixan Ypê Primavera Sachê",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "800 g",
  "price": 6.16,
  "listPrice": 7.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0096",
  "desc": "Tixan · Sabão em Pó · 800 g · 20 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0097",
  "name": "Lava Roupas em Pó Tixan Ypê Pro",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0097",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0098",
  "name": "Lava Roupas em Pó Tixan Maciez",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0098",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0099",
  "name": "Lava Roupas em Pó Tixan Ypê Pro Sensitive",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0099",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0100",
  "name": "Lava Roupas em Pó Tixan Ypê Sensitive",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0100",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0101",
  "name": "Lava Roupas em Pó Tixan Ypê Green",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Tixan",
  "package": "1 kg",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0101",
  "desc": "Tixan · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0102",
  "name": "Lava Roupas em Pó Atol Coco",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Atol",
  "package": "1 kg",
  "price": 5.84,
  "listPrice": 7.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_atol-sabao-em-pasta-atol-1727787622.png",
  "link": "ype-0102",
  "desc": "Atol · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0103",
  "name": "Lava Roupas em Pó Atol Lavanda",
  "category": "Lavanderia",
  "family": "Sabão em Pó",
  "brand": "Atol",
  "package": "1 kg",
  "price": 5.84,
  "listPrice": 7.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_atol-sabao-em-pasta-atol-1727787622.png",
  "link": "ype-0103",
  "desc": "Atol · Sabão em Pó · 1 kg · 16 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0104",
  "name": "Lava Roupas Líquido Ypê Power Act",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Ypê",
  "package": "3 L",
  "price": 19.42,
  "listPrice": 24.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0104",
  "desc": "Ypê · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0105",
  "name": "Lava Roupas Líquido Ypê Power Act Refil",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Ypê",
  "package": "3 L",
  "price": 17.86,
  "listPrice": 22.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0105",
  "desc": "Ypê · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0106",
  "name": "Lava Roupas Líquido Tixan Maciez Refil",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 16.30,
  "listPrice": 20.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0106",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0107",
  "name": "Lava Roupas Líquido Tixan Power Act",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 18.64,
  "listPrice": 23.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0107",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0108",
  "name": "Lava Roupas Líquido Tixan Power Act Refil",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.08,
  "listPrice": 21.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0108",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0109",
  "name": "Lava Roupas Líquido Tixan Primavera",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 15.52,
  "listPrice": 19.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0109",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0110",
  "name": "Lava Roupas Líquido Tixan Primavera Refil",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 13.96,
  "listPrice": 17.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0110",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0111",
  "name": "Lava Roupas Líquido Tixan Ypê Antibac Refil",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.08,
  "listPrice": 21.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0111",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0112",
  "name": "Lava Roupas Líquido Tixan Ypê Coco e Baunilha",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.08,
  "listPrice": 21.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_coco_e_baunilha.png",
  "link": "ype-0112",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0113",
  "name": "Lava Roupas Líquido Tixan Ypê Express: Combate mau odor",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.86,
  "listPrice": 22.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0113",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0114",
  "name": "Lava Roupas Líquido Tixan Ypê Express: Cuida das roupas",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.86,
  "listPrice": 22.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0114",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0115",
  "name": "Lava Roupas Líquido Tixan Maciez",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 15.52,
  "listPrice": 19.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0115",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0116",
  "name": "Lava Roupas Líquido Tixan Ypê Antibac",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 17.86,
  "listPrice": 22.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0116",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0117",
  "name": "Lava Roupas Líquido Tixan Ypê Green",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Tixan",
  "package": "3 L",
  "price": 19.42,
  "listPrice": 24.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0117",
  "desc": "Tixan · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0118",
  "name": "Lava Roupas Líquido Atol",
  "category": "Lavanderia",
  "family": "Sabão Líquido",
  "brand": "Atol",
  "package": "3 L",
  "price": 13.18,
  "listPrice": 16.90,
  "available": true,
  "image": "assets/cat-lavanderia.svg",
  "link": "ype-0118",
  "desc": "Atol · Sabão Líquido · 3 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0120",
  "name": "Tira Manchas em Gel Tixan Ypê Roupas Brancas e Coloridas",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 ml",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0120",
  "desc": "Tixan · Tira Manchas · 450 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0121",
  "name": "Tira Manchas em Gel Tixan Ypê Roupas Brancas",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 ml",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0121",
  "desc": "Tixan · Tira Manchas · 450 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0122",
  "name": "Tira Manchas em Gel Tixan Ypê Roupas Brancas Refil",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0122",
  "desc": "Tixan · Tira Manchas · 450 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0123",
  "name": "Tira Manchas em Pó Tixan Ypê Roupas Brancas e Coloridas",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 g",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0123",
  "desc": "Tixan · Tira Manchas · 450 g · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0124",
  "name": "Tira Manchas em Pó Tixan Ypê Roupas Brancas",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 g",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0124",
  "desc": "Tixan · Tira Manchas · 450 g · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0125",
  "name": "Tira Manchas em Pó Tixan Ypê Roupas Brancas Sachê",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "200 g",
  "price": 3.82,
  "listPrice": 4.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0125",
  "desc": "Tixan · Tira Manchas · 200 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0126",
  "name": "Tira Manchas em Gel Tixan Ypê Roupas Brancas e Coloridas Refil",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "450 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0126",
  "desc": "Tixan · Tira Manchas · 450 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0127",
  "name": "Tira Manchas em Pó Tixan Ypê Roupas Brancas e Coloridas Sachê",
  "category": "Lavanderia",
  "family": "Tira Manchas",
  "brand": "Tixan",
  "package": "200 g",
  "price": 3.82,
  "listPrice": 4.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_tixan_tira_manchas_roupas-brancas-e-coloridas.png",
  "link": "ype-0127",
  "desc": "Tixan · Tira Manchas · 200 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0034",
  "name": "Detergente Ypê Neutro",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0034",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0035",
  "name": "Detergente com Enzimas Ativas Ypê Platinum",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0035",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0036",
  "name": "Detergente com Enzimas Ativas Ypê Titanium",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0036",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0037",
  "name": "Detergente Ypê Clear",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0037",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0038",
  "name": "Detergente Ypê Coco",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0038",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0039",
  "name": "Detergente Ypê Limão",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0039",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0040",
  "name": "Detergente Ypê Maçã",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0040",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0041",
  "name": "Detergente Ypê Clear Care",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0041",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0042",
  "name": "Detergente Ypê Capim-limão",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0042",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0043",
  "name": "Detergente Ypê Pro",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0043",
  "desc": "Ypê · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0044",
  "name": "Detergente Atol Neutro",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Atol",
  "package": "500 ml",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0044",
  "desc": "Atol · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0045",
  "name": "Detergente Atol Coco",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Atol",
  "package": "500 ml",
  "price": 2.10,
  "listPrice": 2.69,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0045",
  "desc": "Atol · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0046",
  "name": "Detergente Atol Maçã",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Atol",
  "package": "500 ml",
  "price": 2.10,
  "listPrice": 2.69,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0046",
  "desc": "Atol · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0047",
  "name": "Detergente Atol Limão",
  "category": "Cozinha",
  "family": "Detergente",
  "brand": "Atol",
  "package": "500 ml",
  "price": 2.10,
  "listPrice": 2.69,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0047",
  "desc": "Atol · Detergente · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0048",
  "name": "Detergente Concentrado Ypê Green",
  "category": "Cozinha",
  "family": "Detergente Concentrado",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_detergente_concentrado_green.png",
  "link": "ype-0048",
  "desc": "Ypê · Detergente Concentrado · 200 ml · 24 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0049",
  "name": "Detergente Concentrado Ypê Neutro+",
  "category": "Cozinha",
  "family": "Detergente Concentrado",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 4.13,
  "listPrice": 5.29,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_detergente_concentrado_neutro.png",
  "link": "ype-0049",
  "desc": "Ypê · Detergente Concentrado · 200 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0050",
  "name": "Detergente Concentrado Ypê Antibac",
  "category": "Cozinha",
  "family": "Detergente Concentrado",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0050",
  "desc": "Ypê · Detergente Concentrado · 200 ml · 24 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0051",
  "name": "Detergente Concentrado Ypê Clear+",
  "category": "Cozinha",
  "family": "Detergente Concentrado",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_detergente_concentrado_clear-1738070861.png",
  "link": "ype-0051",
  "desc": "Ypê · Detergente Concentrado · 200 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0052",
  "name": "Detergente para Máquina de Lavar Louças Ypê",
  "category": "Cozinha",
  "family": "Detergente em Pó p/ Máquina",
  "brand": "Ypê",
  "package": "500 g",
  "price": 14.74,
  "listPrice": 18.90,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0052",
  "desc": "Ypê · Detergente em Pó p/ Máquina · 500 g · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0053",
  "name": "Esponja Ypê Multiuso",
  "category": "Cozinha",
  "family": "Esponja",
  "brand": "Ypê",
  "package": "1 un",
  "price": 1.01,
  "listPrice": 1.29,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0053",
  "desc": "Ypê · Esponja · 1 un · 60 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0054",
  "name": "Esponja Ypê Não Risca Antibac",
  "category": "Cozinha",
  "family": "Esponja",
  "brand": "Ypê",
  "package": "1 un",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0054",
  "desc": "Ypê · Esponja · 1 un · 60 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0055",
  "name": "Esponja Multiuso Assolan Pertuto",
  "category": "Cozinha",
  "family": "Esponja",
  "brand": "Assolan",
  "package": "pacote c/4",
  "price": 3.89,
  "listPrice": 4.99,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0055",
  "desc": "Assolan · Esponja · pacote c/4 · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0056",
  "name": "Esponja de Lã de Aço Assolan",
  "category": "Cozinha",
  "family": "Lã de Aço",
  "brand": "Assolan",
  "package": "pacote 8 un (60g)",
  "price": 1.79,
  "listPrice": 2.29,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_assolan_la-de-aco_45g.png",
  "link": "ype-0056",
  "desc": "Assolan · Lã de Aço · pacote 8 un (60g) · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0077",
  "name": "Pano Perfex Azul",
  "category": "Cozinha",
  "family": "Pano",
  "brand": "Perfex",
  "package": "pacote c/5",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0077",
  "desc": "Perfex · Pano · pacote c/5 · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0078",
  "name": "Pano Perfex Rosa",
  "category": "Cozinha",
  "family": "Pano",
  "brand": "Perfex",
  "package": "pacote c/5",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0078",
  "desc": "Perfex · Pano · pacote c/5 · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0079",
  "name": "Pano Perfex +Cores",
  "category": "Cozinha",
  "family": "Pano",
  "brand": "Perfex",
  "package": "pacote c/5",
  "price": 6.16,
  "listPrice": 7.90,
  "available": true,
  "image": "assets/cat-cozinha.svg",
  "link": "ype-0079",
  "desc": "Perfex · Pano · pacote c/5 · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0001",
  "name": "Água Sanitária Ypê",
  "category": "Limpeza Pesada",
  "family": "Água Sanitária",
  "brand": "Ypê",
  "package": "1 L",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0001",
  "desc": "Ypê · Água Sanitária · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0002",
  "name": "Água Sanitária Ypê Pro",
  "category": "Limpeza Pesada",
  "family": "Água Sanitária",
  "brand": "Ypê",
  "package": "2 L",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_agua_sanitaria_pro_2025.png",
  "link": "ype-0002",
  "desc": "Ypê · Água Sanitária · 2 L · 6 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0024",
  "name": "Desinfetante Ypê Pinho Citrus",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.50,
  "listPrice": 4.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-pinho-500ml-citrus.png",
  "link": "ype-0024",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0025",
  "name": "Desinfetante Ypê Pinho Tradição",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.50,
  "listPrice": 4.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-pinho-500ml-tradicao-1738004077.png",
  "link": "ype-0025",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0026",
  "name": "Desinfetante Ypê BAK Lavanda",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-bak-500ml-lavanda.png",
  "link": "ype-0026",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0027",
  "name": "Desinfetante Ypê BAK Eucalipto",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-bak-500ml-eucalipto.png",
  "link": "ype-0027",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0028",
  "name": "Desinfetante Ypê BAK Floral",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-bak-500ml-floral.png",
  "link": "ype-0028",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0029",
  "name": "Desinfetante Ypê BAK Turquesa",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.28,
  "listPrice": 5.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-bak-500ml-turquesa.png",
  "link": "ype-0029",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0030",
  "name": "Desinfetante Ypê Pinho Lavanda",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.50,
  "listPrice": 4.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_desinfetante-pinho-500ml-lavanda.png",
  "link": "ype-0030",
  "desc": "Ypê · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0031",
  "name": "Desinfetante Perfumado Atol Ciranda de Cheiros",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Atol",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0031",
  "desc": "Atol · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0032",
  "name": "Desinfetante Perfumado Atol Rendas de Lavanda",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Atol",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0032",
  "desc": "Atol · Desinfetante · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0033",
  "name": "Desinfetante Perfumado Atol Cordel de Flores",
  "category": "Limpeza Pesada",
  "family": "Desinfetante",
  "brand": "Atol",
  "package": "90 ml",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0033",
  "desc": "Atol · Desinfetante · 90 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0057",
  "name": "Limpador Multiuso Ypê Desengordurante",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0057",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0058",
  "name": "Limpador Multiuso Ypê Green",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0058",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0059",
  "name": "Limpador Multiuso Ypê Antibac",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0059",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0060",
  "name": "Limpador Multiuso Ypê Controle de Odor",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0060",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0061",
  "name": "Limpador Multiuso Ypê Tira Manchas",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_multiuso-tira-manchas-rosa.png",
  "link": "ype-0061",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0062",
  "name": "Limpador Multiuso Ypê + Limpa Vidros com Álcool",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 3.11,
  "listPrice": 3.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_multiuso-limpa_vidros_abril-1745342148.png",
  "link": "ype-0062",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0063",
  "name": "Limpador Multiuso Ypê Perfumes",
  "category": "Limpeza Pesada",
  "family": "Limpador Multiuso",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0063",
  "desc": "Ypê · Limpador Multiuso · 500 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0064",
  "name": "Limpador Perfumado Ypê Jardim Secreto",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0064",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0065",
  "name": "Limpador Perfumado Ypê Azul Tropical",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0065",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0066",
  "name": "Limpador Perfumado Ypê Doce Vida",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0066",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0067",
  "name": "Limpador Perfumado Ypê Amor de Verão",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_amor_de_verao.png",
  "link": "ype-0067",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0068",
  "name": "Limpador Perfumado Ypê Chá Branco",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0068",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0069",
  "name": "Limpador Perfumado Ypê Pro",
  "category": "Limpeza Pesada",
  "family": "Limpador Perfumado",
  "brand": "Ypê",
  "package": "500 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0069",
  "desc": "Ypê · Limpador Perfumado · 500 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0070",
  "name": "Limpeza Pesada Ypê Original",
  "category": "Limpeza Pesada",
  "family": "Limpeza Pesada",
  "brand": "Ypê",
  "package": "1 L",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0070",
  "desc": "Ypê · Limpeza Pesada · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0071",
  "name": "Limpeza Pesada Ypê Lemon Extreme",
  "category": "Limpeza Pesada",
  "family": "Limpeza Pesada",
  "brand": "Ypê",
  "package": "1 L",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0071",
  "desc": "Ypê · Limpeza Pesada · 1 L · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0072",
  "name": "Lustra-Móveis Ypê Lavanda",
  "category": "Limpeza Pesada",
  "family": "Lustra-Móveis",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_lustra-moveis-lavanda-1725393614.png",
  "link": "ype-0072",
  "desc": "Ypê · Lustra-Móveis · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0073",
  "name": "Lustra-Móveis Ypê Jasmin",
  "category": "Limpeza Pesada",
  "family": "Lustra-Móveis",
  "brand": "Ypê",
  "package": "200 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_lustra-moveis-jasmin-1725393558.png",
  "link": "ype-0073",
  "desc": "Ypê · Lustra-Móveis · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0074",
  "name": "Saponáceo Ypê Multiuso Cremoso Original",
  "category": "Limpeza Pesada",
  "family": "Multiuso Cremoso (Saponáceo)",
  "brand": "Ypê",
  "package": "300 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0074",
  "desc": "Ypê · Multiuso Cremoso (Saponáceo) · 300 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0075",
  "name": "Saponáceo Ypê Multiuso Cremoso Citrus",
  "category": "Limpeza Pesada",
  "family": "Multiuso Cremoso (Saponáceo)",
  "brand": "Ypê",
  "package": "300 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0075",
  "desc": "Ypê · Multiuso Cremoso (Saponáceo) · 300 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0076",
  "name": "Saponáceo Ypê Multiuso Cremoso Lavanda",
  "category": "Limpeza Pesada",
  "family": "Multiuso Cremoso (Saponáceo)",
  "brand": "Ypê",
  "package": "300 ml",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0076",
  "desc": "Ypê · Multiuso Cremoso (Saponáceo) · 300 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0119",
  "name": "Tira Limo Ypê Cloro Ativo Gel",
  "category": "Limpeza Pesada",
  "family": "Tira Limo",
  "brand": "Ypê",
  "package": "500 g",
  "price": 6.16,
  "listPrice": 7.90,
  "available": true,
  "image": "assets/cat-limpeza-pesada.svg",
  "link": "ype-0119",
  "desc": "Ypê · Tira Limo · 500 g · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0128",
  "name": "Desodorante Antitranspirante em Creme Feminino Banho a Banho: Intensive Protect",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Creme",
  "brand": "Banho a Banho",
  "package": "55 g",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0128",
  "desc": "Banho a Banho · Desodorante Creme · 55 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0129",
  "name": "Desodorante Antitranspirante em Creme Feminino Banho a Banho: Ultra Care",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Creme",
  "brand": "Banho a Banho",
  "package": "55 g",
  "price": 4.60,
  "listPrice": 5.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0129",
  "desc": "Banho a Banho · Desodorante Creme · 55 g · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0130",
  "name": "Desodorante Roll-on Feminino Banho a Banho: Active Dry",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Roll-on",
  "brand": "Banho a Banho",
  "package": "50 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0130",
  "desc": "Banho a Banho · Desodorante Roll-on · 50 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0131",
  "name": "Desodorante Roll-on Feminino Banho a Banho: Intensive Protect",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Roll-on",
  "brand": "Banho a Banho",
  "package": "50 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0131",
  "desc": "Banho a Banho · Desodorante Roll-on · 50 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0132",
  "name": "Desodorante Roll-on Feminino Banho a Banho: Ultra Care",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Roll-on",
  "brand": "Banho a Banho",
  "package": "50 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0132",
  "desc": "Banho a Banho · Desodorante Roll-on · 50 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0133",
  "name": "Desodorante Roll-on Masculino Banho a Banho: Extreme Fresh",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Roll-on",
  "brand": "Banho a Banho",
  "package": "50 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0133",
  "desc": "Banho a Banho · Desodorante Roll-on · 50 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0134",
  "name": "Desodorante Roll-on Masculino Banho a Banho: Power Dry",
  "category": "Cuidados Pessoais",
  "family": "Desodorante Roll-on",
  "brand": "Banho a Banho",
  "package": "50 ml",
  "price": 5.38,
  "listPrice": 6.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0134",
  "desc": "Banho a Banho · Desodorante Roll-on · 50 ml · 24 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0135",
  "name": "Hidratante Corporal Flor de Ypê Ameixa e Flor de Lótus",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0135",
  "desc": "Flor de Ypê · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0136",
  "name": "Hidratante Corporal Flor de Ypê Karité e Flor de Amêndoas",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0136",
  "desc": "Flor de Ypê · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0137",
  "name": "Hidratante Corporal Flor de Ypê Água de Coco e Aloe Vera",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0137",
  "desc": "Flor de Ypê · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0138",
  "name": "Loção Deo Hidratante Corporal Banho a Banho: Amêndoas & Pistache",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 10.84,
  "listPrice": 13.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0138",
  "desc": "Banho a Banho · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0139",
  "name": "Loção Deo Hidratante Corporal Banho a Banho: Original",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 10.84,
  "listPrice": 13.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0139",
  "desc": "Banho a Banho · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0140",
  "name": "Loção Deo Hidratante Corporal Banho a Banho: Romã e Ácido Hialurônico",
  "category": "Cuidados Pessoais",
  "family": "Hidratante Corporal",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 10.84,
  "listPrice": 13.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0140",
  "desc": "Banho a Banho · Hidratante Corporal · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0141",
  "name": "Sabonete em Barra Banho a Banho: Amêndoas & Pistache",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Banho a Banho",
  "package": "85 g",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0141",
  "desc": "Banho a Banho · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0142",
  "name": "Sabonete em Barra Banho a Banho: Romã & Ácido Hialurônico",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Banho a Banho",
  "package": "85 g",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0142",
  "desc": "Banho a Banho · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0143",
  "name": "Sabonete Flor de Ypê: Frésia e Pêssego",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-fresia-e-pessego.png",
  "link": "ype-0143",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0144",
  "name": "Sabonete Flor de Ypê: Gardênia e Argan",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-gardenia-e-argan.png",
  "link": "ype-0144",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0145",
  "name": "Sabonete Flor de Ypê: Flor de Laranjeira e Damasco",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-laranjeira-damasco.png",
  "link": "ype-0145",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0146",
  "name": "Sabonete em Barra Banho a Banho: Chá Verde & Aloe Vera",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Banho a Banho",
  "package": "85 g",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-aloe-vera-verde-1745344589.png",
  "link": "ype-0146",
  "desc": "Banho a Banho · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0147",
  "name": "Sabonete Flor de Ypê: Água de Coco e Alecrim",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0147",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0148",
  "name": "Sabonete em Barra Banho a Banho: Original",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Banho a Banho",
  "package": "85 g",
  "price": 1.94,
  "listPrice": 2.49,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0148",
  "desc": "Banho a Banho · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0149",
  "name": "Sabonete Flor de Ypê: Rosas Brancas e Avelã",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-rosas-brancas-avela.png",
  "link": "ype-0149",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0150",
  "name": "Sabonete Flor de Ypê: Flor de Baunilha e Amêndoas",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0150",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0151",
  "name": "Sabonete Flor de Ypê: Flor de Maçã e Framboesa",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.18,
  "listPrice": 2.79,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-maca-framboesa-1748482587.png",
  "link": "ype-0151",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0152",
  "name": "Sabonete Flor de Ypê Vegano Flor de Alecrim",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0152",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0153",
  "name": "Sabonete Flor de Ypê Vegano Cacau e Baunilha",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0153",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0154",
  "name": "Sabonete Flor de Ypê Vegano Limão Siciliano",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-maca-framboesa-1748482587.png",
  "link": "ype-0154",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0155",
  "name": "Sabonete Flor de Ypê Vegano Pitaya",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.72,
  "listPrice": 3.49,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-laranjeira-damasco.png",
  "link": "ype-0155",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0156",
  "name": "Sabonete Flor de Ypê Meu Momento Gengibre e Carvão Ativado",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-gardenia-e-argan.png",
  "link": "ype-0156",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0157",
  "name": "Sabonete Flor de Ypê Meu Momento Lavanda",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-laranjeira-damasco.png",
  "link": "ype-0157",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0158",
  "name": "Sabonete Flor de Ypê Meu Momento Mandarina",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.57,
  "listPrice": 3.29,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0158",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0159",
  "name": "Sabonete com Hidratante Flor de Ypê Água de Coco e Aloe Vera",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-agua-de-coco-e-alecrim.png",
  "link": "ype-0159",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0160",
  "name": "Sabonete com Hidratante Flor de Ypê Karité e Flor de Amêndoas",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0160",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0161",
  "name": "Sabonete com Hidratante Flor de Ypê Ameixa e Flor de Lótus",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Flor de Ypê",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-de-baunilha-e-amendoas.png",
  "link": "ype-0161",
  "desc": "Flor de Ypê · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0162",
  "name": "Sabonete Antibacteriano Action de Ypê Limpeza Profunda",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Action",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-maca-framboesa-1748482587.png",
  "link": "ype-0162",
  "desc": "Action · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0163",
  "name": "Sabonete Antibacteriano Action de Ypê Carvão Detox",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Action",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-gardenia-e-argan.png",
  "link": "ype-0163",
  "desc": "Action · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0164",
  "name": "Sabonete Antibacteriano Action de Ypê Pétalas de Rosa",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Action",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-gardenia-e-argan.png",
  "link": "ype-0164",
  "desc": "Action · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0165",
  "name": "Sabonete Antibacteriano Action de Ypê Capim-Limão",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Action",
  "package": "85 g",
  "price": 2.33,
  "listPrice": 2.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-flor-laranjeira-damasco.png",
  "link": "ype-0165",
  "desc": "Action · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0166",
  "name": "Sabonete Antibac Siene: Aloe",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-antibac-aloe.png",
  "link": "ype-0166",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": true
 },
 {
  "id": "YPE-0167",
  "name": "Sabonete com Hidratante Siene: Macadâmia",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-hidrat-macadamia.png",
  "link": "ype-0167",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0168",
  "name": "Sabonete com Hidratante Siene: Proteínas do Leite",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-hidrat-proteinas-leite.png",
  "link": "ype-0168",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0169",
  "name": "Sabonete Perfumado Siene: Rosas Vermelhas",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-perfum-rosas-vermelhas.png",
  "link": "ype-0169",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0170",
  "name": "Sabonete Perfumado Siene: Erva Doce",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-perfum-erva-doce.png",
  "link": "ype-0170",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0171",
  "name": "Sabonete Perfumado Siene: Lavanda",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-perfum-lavanda.png",
  "link": "ype-0171",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0172",
  "name": "Sabonete com Hidratante Siene: Flor de Algodão",
  "category": "Cuidados Pessoais",
  "family": "Sabonete em Barra",
  "brand": "Siene",
  "package": "85 g",
  "price": 1.55,
  "listPrice": 1.99,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-siene-85g-hidrat-flor-algodao.png",
  "link": "ype-0172",
  "desc": "Siene · Sabonete em Barra · 85 g · 48 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0173",
  "name": "Sabonete Líquido Flor de Ypê: Rosas Brancas e Avelã",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-rosas-brancas-avela.png",
  "link": "ype-0173",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0174",
  "name": "Sabonete Líquido Flor de Ypê: Flor de Maçã e Framboesa",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-flor-maca-framboesa.png",
  "link": "ype-0174",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0175",
  "name": "Sabonete Líquido Hidratante Banho a Banho: Original",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0175",
  "desc": "Banho a Banho · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0176",
  "name": "Sabonete Líquido Flor de Ypê: Flor de Laranjeira e Damasco (Refil)",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 6.94,
  "listPrice": 8.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-flior-laranjeira-damasco.png",
  "link": "ype-0176",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0177",
  "name": "Sabonete Líquido Hidratante Banho a Banho: Chá Verde & Aloe Vera",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabao-barra-aloe-vera-verde-1745344589.png",
  "link": "ype-0177",
  "desc": "Banho a Banho · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0178",
  "name": "Sabonete Líquido Flor de Ypê: Frésia e Pêssego",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_barra-flor-de-ype-85g-fresia-e-pessego.png",
  "link": "ype-0178",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0179",
  "name": "Sabonete Líquido Hidratante Banho a Banho: Amêndoas & Pistache",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 9.28,
  "listPrice": 11.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0179",
  "desc": "Banho a Banho · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0180",
  "name": "Sabonete Líquido Flor de Ypê: Água de Coco e Alecrim",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 7.72,
  "listPrice": 9.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-agua-de-coco-e-alecrim.png",
  "link": "ype-0180",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0181",
  "name": "Sabonete Líquido Vegano Flor de Ypê Pitaya",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-agua-de-coco-e-alecrim.png",
  "link": "ype-0181",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0182",
  "name": "Sabonete Líquido Vegano Flor de Ypê Limão Siciliano",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Flor de Ypê",
  "package": "200 ml",
  "price": 10.06,
  "listPrice": 12.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-rosas-brancas-avela.png",
  "link": "ype-0182",
  "desc": "Flor de Ypê · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0183",
  "name": "Sabonete Líquido Action de Ypê Limpeza Profunda",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Action",
  "package": "200 ml",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-rosas-brancas-avela.png",
  "link": "ype-0183",
  "desc": "Action · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0184",
  "name": "Sabonete Líquido Action de Ypê Carvão Detox",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido",
  "brand": "Action",
  "package": "200 ml",
  "price": 8.50,
  "listPrice": 10.90,
  "available": true,
  "image": "https://www.ype.ind.br/assets-NS/card_sabonete_lidquido-flor-de-ype-250ml-agua-de-coco-e-alecrim.png",
  "link": "ype-0184",
  "desc": "Action · Sabonete Líquido · 200 ml · 12 un/cx",
  "recommended": false
 },
 {
  "id": "YPE-0185",
  "name": "Sabonete Líquido em Óleo Banho a Banho",
  "category": "Cuidados Pessoais",
  "family": "Sabonete Líquido em Óleo",
  "brand": "Banho a Banho",
  "package": "200 ml",
  "price": 11.62,
  "listPrice": 14.90,
  "available": true,
  "image": "assets/cat-cuidados-pessoais.svg",
  "link": "ype-0185",
  "desc": "Banho a Banho · Sabonete Líquido em Óleo · 200 ml · 12 un/cx",
  "recommended": false
 }
];
window.CASTELO_PRODUCTS = window.YPE_PRODUCTS;
