// Catálogo Castelo Alimentos — extraído via API VTEX em 2026-06-01
// Total: 107 produtos
window.CASTELO_PRODUCTS = [
 {
  "id": "58",
  "name": "Óleo Composto de Soja e Azeite de Oliva Castelo 500ml",
  "category": "Azeites e Óleo",
  "price": 10.61,
  "listPrice": 10.61,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155670/mockup-oleo-misto.png?v=637598956389170000",
  "link": "oleo-composto-soja-azeite-oliva-500ml",
  "desc": "O Óleo Composto Castelo é ideal para temperar, refogar ou ir à mesa. Tem como composição 10% de azeite de oliva mais 90%",
  "recommended": true
 },
 {
  "id": "114",
  "name": "Azeite de Oliva Extra Virgem Castelo 250ml",
  "category": "Azeites e Óleo",
  "price": 20.03,
  "listPrice": 20.03,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155973/250ml.jpg?v=638364271095230000",
  "link": "azeite-oliva-extra-virgem-250ml-copy-114-",
  "desc": "O Azeite de Oliva Extra Virgem Castelo é extraído de azeitonas portuguesas colhidas e selecionadas especialmente para of",
  "recommended": false
 },
 {
  "id": "29",
  "name": "Azeite de Oliva Extra Virgem Castelo 500ml",
  "category": "Azeites e Óleo",
  "price": 30.04,
  "listPrice": 33.38,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155583/azeite_extravirgem.jpg?v=637575642272330000",
  "link": "azeite-oliva-extra-virgem-500ml",
  "desc": "O Azeite de Oliva Extra Virgem Castelo é extraído de azeitonas portuguesas colhidas e selecionadas especialmente para of",
  "recommended": false
 },
 {
  "id": "28",
  "name": "Azeite de Oliva Castelo 500ml",
  "category": "Azeites e Óleo",
  "price": 30.48,
  "listPrice": 30.48,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155568/azeite_oliva.jpg?v=637575617692300000",
  "link": "azeite-oliva-500ml",
  "desc": "O Azeite de Oliva Castelo é extraído de azeitonas colhidas e selecionadas para oferecer o sabor e o aroma característico",
  "recommended": false
 },
 {
  "id": "119",
  "name": "Azeite Extra Virgem Castelo 500ml + Grátis 250ml",
  "category": "Azeites e Óleo",
  "price": 33.38,
  "listPrice": 33.38,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156057/mk_azeite_extra_virgem_750_promocional_2024--1-.png?v=638603825554230000",
  "link": "azeite-oliva-extra-virgem-500ml-gratis-250ml",
  "desc": "O Azeite de Oliva Extra Virgem Castelo é extraído de azeitonas portuguesas colhidas e selecionadas especialmente para of",
  "recommended": false
 },
 {
  "id": "30",
  "name": "Azeite de Oliva Extra Virgem Castelo Seleção 500ml",
  "category": "Azeites e Óleo",
  "price": 39.19,
  "listPrice": 39.19,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155569/azeite_selecao.jpg?v=637575617702170000",
  "link": "azeite-oliva-extra-virgem-selecao-500ml",
  "desc": "O Azeite de Oliva Extra Virgem Castelo Seleção é extraído de azeitonas portuguesas colhidas e selecionadas especialmente",
  "recommended": false
 },
 {
  "id": "64",
  "name": "Champignon Stand Up Pouch Castelo 80g",
  "category": "Conservas",
  "price": 5.74,
  "listPrice": 5.74,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155482/champignon.jpg?v=637539083223700000",
  "link": "champignon-pouch-80g",
  "desc": "Champignon Castelo é indicado para dar aquele toque especial como acompanhamento de carnes, peixes, panquecas salgadas, ",
  "recommended": true
 },
 {
  "id": "80",
  "name": "Azeitonas Verdes sem Caroço Stand Up Pouch Castelo 150g",
  "category": "Conservas",
  "price": 6.87,
  "listPrice": 6.87,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155468/azeitonaverdesemcaroco.jpg?v=637539051443500000",
  "link": "azeitonas-verdes-sem-caroco-pouch-150g",
  "desc": "As azeitonas Castelo passam\u000bpor um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "82",
  "name": "Azeitonas Verdes Fatiadas Stand Up Pouch Castelo 150g",
  "category": "Conservas",
  "price": 7.19,
  "listPrice": 7.19,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155467/azeitonaverdefatiada.jpg?v=637539051438330000",
  "link": "azeitonas-verdes-fatiadas-pouch-150g",
  "desc": "As azeitonas Castelo passam por um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "63",
  "name": "Champignon Castelo 100g",
  "category": "Conservas",
  "price": 9.3,
  "listPrice": 9.3,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155483/cogumelo.jpg?v=637539083228230000",
  "link": "champignon-castelo-100g",
  "desc": "O Champignon Castelo é muito indicado para dar aquele toque especial como acompanhamento de carnes, peixes, panquecas sa",
  "recommended": false
 },
 {
  "id": "77",
  "name": "Azeitonas Verdes com Caroço Castelo 200g",
  "category": "Conservas",
  "price": 10.31,
  "listPrice": 10.31,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155463/azeitonacomcaroco.jpg?v=637539051418000000",
  "link": "azeitonas-verdes-caroco-200g",
  "desc": "As azeitonas Castelo passam\u000bpor um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "75",
  "name": "Picles Castelo 180g",
  "category": "Conservas",
  "price": 10.41,
  "listPrice": 10.41,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156075/WhatsApp-Image-2024-10-24-at-10.43.57.jpg?v=638653746761800000",
  "link": "picles-300g",
  "desc": "O Picles Castelo possui alto valor nutritivo pois é composto de Cenoura, Nabo, Pepino e Couve-Flor (em proporção variáve",
  "recommended": false
 },
 {
  "id": "65",
  "name": "Pepino Castelo 300g",
  "category": "Conservas",
  "price": 11.69,
  "listPrice": 11.69,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156085/mk_pepino_300g_vidro_low.png.png?v=638724722441770000",
  "link": "pepino",
  "desc": "O Pepino Castelo é rico em vitaminas e possui poucas calorias. Ideal para ser consumido como aperitivo, em saladas, refo",
  "recommended": false
 },
 {
  "id": "79",
  "name": "Azeitonas Verdes sem Caroço Castelo 150g",
  "category": "Conservas",
  "price": 12.24,
  "listPrice": 12.24,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155465/azeitonasemcaroco.jpg?v=637539051428030000",
  "link": "azeitonas-verdes-sem-caroco-150g",
  "desc": "As azeitonas Castelo passam\u000bpor um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "81",
  "name": "Azeitonas Verdes Fatiadas Castelo 160g",
  "category": "Conservas",
  "price": 12.67,
  "listPrice": 12.67,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155464/azeitonafatiada.jpg?v=637539051423000000",
  "link": "azeitonas-verdes-fatiadas-160g",
  "desc": "As azeitonas Castelo passam\u000bpor um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "76",
  "name": "Cebolinha Castelo 190g",
  "category": "Conservas",
  "price": 13.17,
  "listPrice": 13.17,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155481/cebolinha.jpg?v=637539083219470000",
  "link": "cebolinha-190g",
  "desc": "Experimente servir as Cebolinhas Castelo como aperitivo ou como acompanhamento de saladas, carnes e molhos",
  "recommended": false
 },
 {
  "id": "69",
  "name": "Palmito Pupunha Picado Castelo 300g",
  "category": "Conservas",
  "price": 13.6,
  "listPrice": 13.6,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155578/palmito_pupunha_picado.jpg?v=637575617786170000",
  "link": "palmito-pupunha-picado-300g",
  "desc": "O Palmito Pupunha Picado Castelo pode ser utilizado na forma de acompanhamentos para diversificar a apresentação final d",
  "recommended": false
 },
 {
  "id": "70",
  "name": "Palmito Pupunha Rodela Castelo 300g",
  "category": "Conservas",
  "price": 17.04,
  "listPrice": 17.04,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155581/palmito_pupunha_rodela.jpg?v=637575617802130000",
  "link": "palmito-pupunha-rodela-300g",
  "desc": "O Palmito Pupunha Rodela Castelo pode ser utilizado na forma de acompanhamentos para diversificar a apresentação final d",
  "recommended": false
 },
 {
  "id": "67",
  "name": "Palmito Açaí Picado Castelo 300g",
  "category": "Conservas",
  "price": 19.07,
  "listPrice": 19.07,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155576/palmito_acai_picado.jpg?v=637575617775700000",
  "link": "palmito-acai-picado-300g",
  "desc": "O palmito do tipo açaí é selecionado especialmente para incrementar as melhores receitas de tortas, risotos, sopas, sala",
  "recommended": false
 },
 {
  "id": "68",
  "name": "Palmito Pupunha Inteiro Castelo 300g",
  "category": "Conservas",
  "price": 22.06,
  "listPrice": 22.06,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155577/palmito_pupunha.jpg?v=637575617781170000",
  "link": "palmito-pupunha-inteiro-300g",
  "desc": "O Palmito Pupunha Inteiro Castelo pode ser utilizado na forma de acompanhamentos para diversificar a apresentação final ",
  "recommended": false
 },
 {
  "id": "66",
  "name": "Palmito Açaí Inteiro Castelo 300g",
  "category": "Conservas",
  "price": 27.59,
  "listPrice": 27.59,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155575/palmito_acai.jpg?v=637575617769730000",
  "link": "palmito-acai-inteiro-300g",
  "desc": "O Palmito do tipo Açaí é selecionado especialmente para incrementar as melhores receitas e saladas. De corte macio, com ",
  "recommended": false
 },
 {
  "id": "101",
  "name": "Kit Vinagre de Maçã Natural e Vinagre de Maçã  Natural com Mel",
  "category": "Kits",
  "price": 43.58,
  "listPrice": 43.58,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155714/pack_maca_maca_mel_1000x1000.png?v=637654227283200000",
  "link": "kit-vinagre-de-maca-natural-e-vinagre-de-maca-natural-com-mel",
  "desc": "Os Kits Castelo oferecem o melhor custo benefício, permitindo a experimentação dos deliciosos produtos da marca com uma ",
  "recommended": true
 },
 {
  "id": "102",
  "name": "Kit Vinagre Maçã Natural e Vinagre Vinho Tinto com Suco de Uva",
  "category": "Kits",
  "price": 43.59,
  "listPrice": 43.59,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155715/pack_maca_tinto_1000x1000.png?v=637654239644070000",
  "link": "kit-vinagre-maca-natural-e-vinagre-vinho-tinto-com-suco-de-uva-natural-castelo",
  "desc": "Os Kits Castelo oferecem o melhor custo benefício, permitindo a experimentação dos deliciosos produtos da marca com uma ",
  "recommended": false
 },
 {
  "id": "99",
  "name": "Kit Palmito Açaí Inteiro e Creme Balsâmico Tradicional",
  "category": "Kits",
  "price": 44.08,
  "listPrice": 44.08,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155688/kit-palmito-e-balsamico.png?v=637604973421200000",
  "link": "kit-palmito-creme-balsamico",
  "desc": "Os Kits Castelo oferecem o melhor custo benefício, permitindo a experimentação dos deliciosos produtos da marca com uma ",
  "recommended": false
 },
 {
  "id": "100",
  "name": "Kit Azeite Seleção e Vinagre de Maçã com Suco de Maçã e Mel",
  "category": "Kits",
  "price": 55.77,
  "listPrice": 55.77,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155691/azeite-e-vinagre.png?v=637604980017000000",
  "link": "kit-azeite-vinagre-maca-mel",
  "desc": "Os Kits Castelo oferecem o melhor custo benefício, permitindo a experimentação dos deliciosos produtos da marca com uma ",
  "recommended": false
 },
 {
  "id": "51",
  "name": "Molho Inglês Castelo 150ml",
  "category": "Molhos",
  "price": 2.52,
  "listPrice": 2.52,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155938/ingles_150ml.png?v=638260643738630000",
  "link": "molho-ingles-150ml",
  "desc": "O Molho Inglês Castelo é ideal para o preparo de inúmeros pratos à base de carne ou peixe como strogonoffs, sopas, salad",
  "recommended": true
 },
 {
  "id": "54",
  "name": "Molho Shoyu Castelo 150ml",
  "category": "Molhos",
  "price": 2.52,
  "listPrice": 2.52,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155941/shoyu_150ml.png?v=638260645560500000",
  "link": "molho-shoyu-150ml",
  "desc": "O Molho Shoyu Castelo é ideal para o preparo de inúmeros pratos a base de carne ou peixe",
  "recommended": false
 },
 {
  "id": "52",
  "name": "Molho de Alho Castelo 150ml",
  "category": "Molhos",
  "price": 2.52,
  "listPrice": 2.52,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155940/alho_150ml.png?v=638260645125900000",
  "link": "molho-alho-150ml",
  "desc": "O Molho de Alho Castelo é ideal para o preparo de inúmeros pratos à base de carne ou peixe.",
  "recommended": false
 },
 {
  "id": "85",
  "name": "Molho de Mostarda Castelo 200g",
  "category": "Molhos",
  "price": 3.02,
  "listPrice": 3.02,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156087/mk_molho_tradicional_mostarda_200g_2020.jpg.jpg?v=638724727843570000",
  "link": "molho-mostarda-200g",
  "desc": "O Molho de Mostarda é um condimento de qualidade, ideal para acompanhamento de sanduíches, lanches variados e pratos à b",
  "recommended": false
 },
 {
  "id": "84",
  "name": "Molho Barbecue Castelo 200g",
  "category": "Molhos",
  "price": 4.4,
  "listPrice": 4.4,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156081/mk_molho_tradicional_barbecue_200g_2020.jpg.jpg?v=638724716367070000",
  "link": "molho-barbecue-200g",
  "desc": "O Molho Barbecue Castelo é um condimento de sabor inigualável, ideal para acompanhamento de churrascos, lanches variados",
  "recommended": false
 },
 {
  "id": "55",
  "name": "Molho de Pimenta Extra Forte Castelo 60 ml",
  "category": "Molhos",
  "price": 5.81,
  "listPrice": 5.81,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156083/mockup_molho_pimenta_extra_forte_2021.png.png?v=638724718958230000",
  "link": "molho-pimenta-extra-forte-60ml",
  "desc": "O Molho de Pimenta Extra Forte Castelo é obtido através da combinação perfeita das pimentas malagueta e jalapeño.",
  "recommended": false
 },
 {
  "id": "88",
  "name": "Molho Barbecue Top Down Castelo 180g",
  "category": "Molhos",
  "price": 6.26,
  "listPrice": 6.26,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155678/mk_molho_premium_barbecue_180g_2020.png?v=637598984710230000",
  "link": "molho-barbecue-top-down-180g",
  "desc": "Feito com polpa de tomates e condimentos, o Molho Barbecue Castelo tem sabor agridoce, similar à versão norte-americana.",
  "recommended": false
 },
 {
  "id": "89",
  "name": "Molho de Mostarda Top Down Castelo 180g",
  "category": "Molhos",
  "price": 6.27,
  "listPrice": 6.27,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155679/mk_molho_premium_mostarda_180g_2020.png?v=637598985748430000",
  "link": "molho-mostarda-top-down-180g",
  "desc": "O Molho de Mostarda é um condimento de qualidade, ideal para acompanhamento de sanduíches, lanches variados e pratos à b",
  "recommended": false
 },
 {
  "id": "86",
  "name": "Ketchup Castelo 380g",
  "category": "Molhos",
  "price": 6.28,
  "listPrice": 6.28,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156079/mk_molho_tradicional_ketchup_380g_2020.jpg.jpg?v=638724715711270000",
  "link": "ketchup-380g",
  "desc": "Ketchup Castelo é um molho tradicional a base de tomate que adiciona sabor aos seus pratos.",
  "recommended": false
 },
 {
  "id": "50",
  "name": "Molho Lemon Pepper Castelo 200g",
  "category": "Molhos",
  "price": 6.52,
  "listPrice": 6.52,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155937/WhatsApp-Image-2023-07-17-at-11.22.48.jpg?v=638260641111370000",
  "link": "molho-lemon-pepper-200g",
  "desc": "O Molho Lemon Pepper Castelo é uma deliciosa mistura do suco de limão siciliano e pimenta, que resulta em sabor leve com",
  "recommended": false
 },
 {
  "id": "49",
  "name": "Molho Tártaro Castelo 200g",
  "category": "Molhos",
  "price": 6.52,
  "listPrice": 6.52,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155936/WhatsApp-Image-2023-07-17-at-11.22.48--1-.jpg?v=638260640490370000",
  "link": "molho-tartaro-200g",
  "desc": "O Molho Tártaro Castelo com base de maionese e pedacinhos de picles vem pronto para ser utilizado nos mais variados prat",
  "recommended": false
 },
 {
  "id": "116",
  "name": "Molho para Salada Ervas Finas 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156093/mockup_molhos_ervas_finas.png.png?v=638724731287730000",
  "link": "molho-para-salada-ervas-finas-236ml",
  "desc": "O Molho para Salada Castelo Ervas Finas foi elaborado especialmente para as pessoas que apreciam o sabor de ingredientes",
  "recommended": false
 },
 {
  "id": "46",
  "name": "Molho para Salada Caesar Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156131/mockup_molhos_caesar.png.png?v=638724739921270000",
  "link": "molho-para-salada-caesar-236ml",
  "desc": "A salada mais pedida dos restaurantes agora no conforto da sua casa com o Molho para Salada Caesar. O sabor do queijo pa",
  "recommended": false
 },
 {
  "id": "44",
  "name": "Molho para Salada Limão Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156121/mockup_molhos_limao.png.png?v=638724739020400000",
  "link": "molho-para-salada-limao-236ml",
  "desc": "O Molho para Salada Limão Castelo é preparado à base de limão, salsa e cebolinha sendo uma opção refrescante e saborosa ",
  "recommended": false
 },
 {
  "id": "41",
  "name": "Molho para Salada Rosé Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156112/mockup_molhos_rose.png.png?v=638724737843470000",
  "link": "molho-para-salada-rose-236ml",
  "desc": "O Molho Rosé é uma combinação clássica e deliciosa ideal para ser consumido com saladas, legumes cozidos, sanduíches,  i",
  "recommended": false
 },
 {
  "id": "47",
  "name": "Molho para Salada Mostarda e Mel Castelo Leve Vita 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156128/mockup_molhos_mostarda_mel.png.png?v=638724739672230000",
  "link": "molho-para-salada-mostarda-mel-236ml",
  "desc": "Mostarda e mel formam uma dupla imbatível garantindo um molho agridoce perfeito para servir com saladas, carnes e o que ",
  "recommended": false
 },
 {
  "id": "45",
  "name": "Molho para Salada Balsâmico Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156125/mockup_molhos_balsamico.png.png?v=638724739468500000",
  "link": "molho-para-salada-balsamico-236ml",
  "desc": "Molho à base  de vinagre balsâmico e especiarias é ideal para ser utilizado em saladas de folhas verdes, legumes e quant",
  "recommended": false
 },
 {
  "id": "43",
  "name": "Molho para Salada Parmesão Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156115/mockup_molhos_parmesao.png.png?v=638724738075200000",
  "link": "molho-para-salada-parmesao-236ml",
  "desc": "O Molho para Salada Parmesão Castelo possui uma consistência cremosa ideal para legumes, carnes brancas, lanches e em di",
  "recommended": false
 },
 {
  "id": "40",
  "name": "Molho para Salada Caseiro Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156109/mockup_molhos_caseiro.png.png?v=638724737566730000",
  "link": "molho-para-salada-caseiro-236ml",
  "desc": "Molho para Salada Caseiro é o sabor da comida afetiva feita à base de vinagre e especiarias",
  "recommended": false
 },
 {
  "id": "83",
  "name": "Molho 3 em 1 Castelo 380g",
  "category": "Molhos",
  "price": 7.39,
  "listPrice": 7.39,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155673/mk_molho_tradicional_3x1_380g_2020_low.png?v=637598979621330000",
  "link": "molho-3-em-1-380g",
  "desc": "O lanche ganha todo o sabor do ketchup, da mostarda e da maionese juntos, com a praticidade de uma só embalagem.",
  "recommended": false
 },
 {
  "id": "87",
  "name": "Maionese Top Down Castelo 380g",
  "category": "Molhos",
  "price": 7.91,
  "listPrice": 7.91,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155677/mk_molho_premium_maionese_380g_2020.png?v=637598982930530000",
  "link": "maionese-top-down-380g",
  "desc": "A Maionese Premium Castelo complementa com muito sabor: sanduíches, hambúrgueres, saladas de batata, entre outros pratos",
  "recommended": false
 },
 {
  "id": "90",
  "name": "Ketchup Top Down Castelo 380g",
  "category": "Molhos",
  "price": 7.94,
  "listPrice": 7.94,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155680/mk_molho_premium_ketchup_380g_2020.png?v=637598986390400000",
  "link": "ketchup-top-down-380g",
  "desc": "Ketchup Castelo é um molho tradicional a base de tomate que adiciona sabor aos seus pratos.",
  "recommended": false
 },
 {
  "id": "103",
  "name": "Mostarda Gourmet com Manga e Habanero Castelo 240g",
  "category": "Molhos",
  "price": 12.37,
  "listPrice": 12.37,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156061/WhatsApp-Image-2024-08-28-at-8.31.06-AM.jpg?v=638604459968900000",
  "link": "mostarda-gourmet-manga-habanero-240g",
  "desc": "Mostarda Gourmet possui picância nível 1 e sabor suave perfeitamente equilibrado entre a mostarda, a fruta, a pimenta e ",
  "recommended": false
 },
 {
  "id": "131",
  "name": "Molho Chimichurri Castelo Leve Vita 200g",
  "category": "Molhos",
  "price": 12.81,
  "listPrice": 12.81,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156108/mk_molho_chimichurri.png.png?v=638724736480170000",
  "link": "molho-chimichurri-castelo-leve-vita-200g",
  "desc": "Molho Chimichurri Castelo: O Segredo para um Churrasco Inesquecível!\r\n\r\nTradicional na Argentina e no Uruguai, o Molho C",
  "recommended": false
 },
 {
  "id": "96",
  "name": "Patê de Pimenta Biquinho com Habanero e Alho Castelo 230g",
  "category": "Patês Pimenta",
  "price": 11.29,
  "listPrice": 11.29,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155667/mkp_pate_habanero_alho_2020.png?v=637596268583530000",
  "link": "pate-pimenta-biquinho-habanero-alho-230g",
  "desc": "O Patê de Pimenta Biquinho com Habanero e Alho Castelo é feito com pimentas selecionadas, proporcionando um delicioso sa",
  "recommended": true
 },
 {
  "id": "61",
  "name": "Patê de Pimenta Biquinho e Dedo-de-Moça Castelo 220g",
  "category": "Patês Pimenta",
  "price": 11.29,
  "listPrice": 11.29,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155588/pate_pimenta_dedo_moca.jpg?v=637575705302930000",
  "link": "pate-pimenta-biquinho-dedo-moca-220g",
  "desc": "O Patê de Pimenta Biquinho e dedo-de-moça é classificado como nível “6”  de picância, ele possui ardência característico",
  "recommended": false
 },
 {
  "id": "60",
  "name": "Patê de Pimenta Biquinho Levemente Picante Castelo 220g",
  "category": "Patês Pimenta",
  "price": 11.29,
  "listPrice": 11.29,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155591/pate_pimenta_levemente_picante.jpg?v=637581661289230000",
  "link": "pate-pimenta-biquinho-levemente-picante-220g",
  "desc": "O  Patê de Pimenta Biquinho Levemente Picante  é classificado como nível “2”  de picância, possui uma pequena ardência d",
  "recommended": false
 },
 {
  "id": "27",
  "name": "Sumo de Limão Castelo 500 ml",
  "category": "Sumo de Limão",
  "price": 10.44,
  "listPrice": 10.44,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156106/mk_sumo_limao_500ml.png.png?v=638724735323700000",
  "link": "sumo-limao-500ml",
  "desc": "Suco concentrado de 19 limões Taiti. Controle exato de sua dosagem e ainda dura muito mais do que a fruta in natura, poi",
  "recommended": true
 },
 {
  "id": "36",
  "name": "Tempero Completo Sem Pimenta Castelo 300g",
  "category": "Temperos",
  "price": 2.76,
  "listPrice": 2.76,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155503/completosempimenta.jpg?v=637539127254000000",
  "link": "tempero-completo-sem-pimenta-300g",
  "desc": "O Tempero Completo sem Pimenta Castelo foi especialmente desenvolvido para facilitar o preparo das mais variadas receita",
  "recommended": true
 },
 {
  "id": "34",
  "name": "Tempero Completo com Pimenta Castelo 300g",
  "category": "Temperos",
  "price": 2.76,
  "listPrice": 2.76,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155502/completocompimenta.jpg?v=637539127247730000",
  "link": "tempero-completo-pimenta-300g",
  "desc": "O Tempero Completo com Pimenta Castelo é um tempero prático, ideal para quem aprecia pratos mais condimentados",
  "recommended": false
 },
 {
  "id": "38",
  "name": "Tempero Alho e Sal Castelo 300g",
  "category": "Temperos",
  "price": 2.76,
  "listPrice": 2.76,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155500/alhoesal.jpg?v=637539121356870000",
  "link": "tempero-completo-alho-sal-300g",
  "desc": "O Tempero Alho e Sal Castelo é prático para preparar inúmeras receitas no dia-a-dia, desde o arroz até receitas mais sof",
  "recommended": false
 },
 {
  "id": "39",
  "name": "Tempero Alho e Sal Castelo 1kg",
  "category": "Temperos",
  "price": 9.01,
  "listPrice": 9.01,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155641/mk_tempero_pronto_alho_1kg.png?v=637590373309400000",
  "link": "tempero-completo-alho-sal-1kg",
  "desc": "O Tempero Alho e Sal Castelo é prático para preparar inúmeras receitas no dia-a-dia, desde o arroz até receitas mais sof",
  "recommended": false
 },
 {
  "id": "37",
  "name": "Tempero Completo Sem Pimenta Castelo 1kg",
  "category": "Temperos",
  "price": 9.01,
  "listPrice": 9.01,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155571/tempero_completo_sem_pimenta.jpg?v=637575617718900000",
  "link": "tempero-completo-sem-pimenta-1kg",
  "desc": "O Tempero Completo sem Pimenta Castelo foi especialmente desenvolvido para facilitar o preparo das mais variadas receita",
  "recommended": false
 },
 {
  "id": "35",
  "name": "Tempero Completo com Pimenta Castelo 1kg",
  "category": "Temperos",
  "price": 9.01,
  "listPrice": 9.01,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155570/tempero_completo_com_pimenta.jpg?v=637575617712330000",
  "link": "tempero-completo-pimenta-1kg",
  "desc": "O Tempero Completo com Pimenta Castelo é um tempero prático, ideal para quem aprecia pratos mais condimentados",
  "recommended": false
 },
 {
  "id": "1",
  "name": "Vinagre de Álcool Castelo 750ml",
  "category": "Vinagres",
  "price": 4.23,
  "listPrice": 4.23,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155438/alcool.jpg?v=637516767918600000",
  "link": "vinagre-alcool-750ml",
  "desc": "O Vinagre de Álcool Castelo é indicado para acrescentar tempero sem alterar o sabor natural dos alimentos, além de ser p",
  "recommended": true
 },
 {
  "id": "2",
  "name": "Vinagre de Álcool Colorido Castelo 750ml",
  "category": "Vinagres",
  "price": 4.23,
  "listPrice": 4.23,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155437/alcoolcolorido.jpg?v=637516096900170000",
  "link": "vinagre-alcool-colorido-750ml",
  "desc": "Produzido a partir da cana-de-açúcar e é ideal para ser usado nos mais diversos pratos  do dia-a-dia",
  "recommended": false
 },
 {
  "id": "9",
  "name": "Vinagre de Hortelã Castelo 750ml",
  "category": "Vinagres",
  "price": 5.53,
  "listPrice": 5.53,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155445/hortela.jpg?v=637516768023200000",
  "link": "vinagre-hortela-750ml",
  "desc": "O Vinagre de Álcool Aromatizado Colorido  Hortelã Castelo tem um sabor inigualável, aroma especial do hortelã e a qualid",
  "recommended": false
 },
 {
  "id": "7",
  "name": "Vinagre de Limão Castelo 750ml",
  "category": "Vinagres",
  "price": 5.53,
  "listPrice": 5.53,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155443/limao.jpg?v=637516768004600000",
  "link": "vinagre-limao-750ml",
  "desc": "O Vinagre de Álcool com Suco de Limão Castelo é um produto que tem a maneira mais prática e saudável de substituir a fru",
  "recommended": false
 },
 {
  "id": "8",
  "name": "Vinagre de Ervas Finas Castelo 750ml",
  "category": "Vinagres",
  "price": 5.54,
  "listPrice": 5.54,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155444/ervasfinas.jpg?v=637516768012900000",
  "link": "vinagre-ervas-finas-750ml",
  "desc": "O Vinagre de Ervas Finas Castelo é produzido com ervas naturais de manjericão e alecrim. Com sabor suave natural das erv",
  "recommended": false
 },
 {
  "id": "10",
  "name": "Vinagre de Alho Castelo 750ml",
  "category": "Vinagres",
  "price": 5.54,
  "listPrice": 5.54,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155446/alho.jpg?v=637516768029770000",
  "link": "vinagre-alho-750ml",
  "desc": "O Vinagre de Álcool com Alho Castelo é um produto que foi desenvolvido para pessoas que apreciam o sabor e o aroma de al",
  "recommended": false
 },
 {
  "id": "5",
  "name": "Vinagre de Arroz Castelo 750ml",
  "category": "Vinagres",
  "price": 7.19,
  "listPrice": 7.19,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155441/arroz.jpg?v=637516767953600000",
  "link": "vinagre-arroz-750ml",
  "desc": "O Vinagre de Cereal Arroz Castelo possui um sabor suave e é bastante apreciado na cozinha oriental.",
  "recommended": false
 },
 {
  "id": "148",
  "name": "Vinagre de Fruta Maçã Sem Conservantes Castelo Leve Vita 400ml",
  "category": "Vinagres",
  "price": 7.52,
  "listPrice": 8.5,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156161/mockup_vinagre_natural_400ml.png?v=638878690656500000",
  "link": "vinagre-de-fruta-maca-sem-conservantes-castelo-leve-vita-400ml",
  "desc": "Descubra a nova versão do nosso clássico vinagre de maçã, agora em frasco PET de 400ml! O Vinagre de Fruta Maçã Sem Cons",
  "recommended": false
 },
 {
  "id": "6",
  "name": "Vinagre de Maçã Castelo 750ml",
  "category": "Vinagres",
  "price": 7.89,
  "listPrice": 7.89,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155442/maca.jpg?v=637516767990200000",
  "link": "vinagre-maca-750ml",
  "desc": "O Vinagre de Fruta Maçã Castelo é um produto 100% saudável, que ajuda no bom funcionamento do organismo",
  "recommended": false
 },
 {
  "id": "4",
  "name": "Vinagre de Vinho Branco Castelo 750ml",
  "category": "Vinagres",
  "price": 8.04,
  "listPrice": 8.04,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155440/vinhobranco.jpg?v=637516767943930000",
  "link": "vinagre-vinho-branco-750ml",
  "desc": "O Vinagre de Vinho Branco Castelo é 100% produzido a partir do vinho de uvas selecionadas. Resgatam a tradição na fabric",
  "recommended": false
 },
 {
  "id": "3",
  "name": "Vinagre de Vinho Tinto Castelo 750ml",
  "category": "Vinagres",
  "price": 8.04,
  "listPrice": 8.04,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155439/vinhotinto.jpg?v=637516767934230000",
  "link": "vinagre-vinho-tinto-750ml",
  "desc": "O Vinagre de Vinho Tinto Castelo é 100% produzido a partir do vinho de uvas selecionadas, são envelhecidos lentamente pa",
  "recommended": false
 },
 {
  "id": "12",
  "name": "Vinagre de Vinho Tinto Castelo 500ml",
  "category": "Vinagres",
  "price": 11.58,
  "listPrice": 11.58,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155453/vinagremesatinto.jpg?v=637539033193830000",
  "link": "vinagre-vinho-tinto-500ml",
  "desc": "O Vinagre de Vinho Tinto Castelo é 100% produzido a partir do vinho de uvas selecionadas. Resgatam a tradição na fabrica",
  "recommended": false
 },
 {
  "id": "11",
  "name": "Vinagre de Vinho Branco Castelo 500ml",
  "category": "Vinagres",
  "price": 11.58,
  "listPrice": 11.58,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155452/vinagremesabranco.jpg?v=637539033186000000",
  "link": "vinagre-vinho-branco-500ml",
  "desc": "O Vinagre de Vinho Branco Castelo é 100% produzido a partir do vinho de uvas selecionadas. Resgatam a tradição na fabric",
  "recommended": false
 },
 {
  "id": "13",
  "name": "Vinagre de Maçã Castelo 500ml",
  "category": "Vinagres",
  "price": 11.9,
  "listPrice": 11.9,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155454/vinagremesamaca.jpg?v=637539033199000000",
  "link": "vinagre-maca-500ml",
  "desc": "O Vinagre de Maçã Castelo é um produto 100% saudável, que ajuda no bom funcionamento do organismo",
  "recommended": false
 },
 {
  "id": "32",
  "name": "Vinagre de Álcool Aromatizado Maçã Verde 6% Castelo 2l",
  "category": "Vinagres",
  "price": 12.33,
  "listPrice": 12.33,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155510/maca2lg.jpg?v=637539134489070000",
  "link": "vinagre-alcool-maca-verde-6-2l",
  "desc": "Vinagre de Álcool Aromatizado Maçã Verde 6% é a solução ecológica e de múltiplos usos para sua casa. Possui um agradável",
  "recommended": false
 },
 {
  "id": "133",
  "name": "Vinagre de Álcool Aromatizado Citrus 6% Castelo 2l",
  "category": "Vinagres",
  "price": 12.33,
  "listPrice": 12.33,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156134/mk_concentrado_citrus_2l--3---1-.png.png?v=638731539749500000",
  "link": "vinagre-alcool-citrus-6-2l",
  "desc": "Vinagre de Álcool Aromatizado Citrus 6% é a solução ecológica e de múltiplos usos para sua casa. Possui um agradável aro",
  "recommended": false
 },
 {
  "id": "21",
  "name": "Vinagre Balsâmico Tradizionale Castelo 250ml",
  "category": "Vinagres",
  "price": 15.57,
  "listPrice": 15.57,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155460/balsamico250.jpg?v=637539051399400000",
  "link": "vinagre-balsamico-tradizionale-250ml",
  "desc": "Elaborado a partir de vinagre de vinho tinto e extratos vegetais de altíssima qualidade, sendo concebido com a mais avan",
  "recommended": false
 },
 {
  "id": "19",
  "name": "Vinagre de Vinho Tinto Orgânico Castelo Leve Vita 250ml",
  "category": "Vinagres",
  "price": 16.36,
  "listPrice": 16.36,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155450/tintoorganico.jpg?v=637516768060600000",
  "link": "vinagre-vinho-tinto-organico-250ml",
  "desc": "O Vinagre de Vinho Tinto Orgânico Castelo é obtido por meio da fermentação lenta e gradual do vinho tinto orgânico. Sem ",
  "recommended": false
 },
 {
  "id": "149",
  "name": "Vinagre de Fruta Maçã Orgânico Castelo Leve Vita 400ml",
  "category": "Vinagres",
  "price": 17.8,
  "listPrice": 17.8,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156162/mockup_vinagre_organico_400ml.png?v=638878692691000000",
  "link": "vinagre-de-fruta-maca-organico-castelo-leve-vita-400ml",
  "desc": "O vinagre de maçã orgânico que você já conhece, agora mais acessível e prático! O Vinagre de Fruta Maçã Orgânico Castelo",
  "recommended": false
 },
 {
  "id": "57",
  "name": "Tempero de Vinagre Ardente Castelo Leve Vita 450ml",
  "category": "Vinagres",
  "price": 19.14,
  "listPrice": 19.14,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155706/Tenpero-de-Vinagre-Ardente.png?v=637644620029500000",
  "link": "tempero-vinagre-ardente-450ml",
  "desc": "O Tempero de Vinagre Ardente possui pimenta do reino e pimenta malagueta para dar aquela apimentada nas suas receitas!\r\n",
  "recommended": false
 },
 {
  "id": "56",
  "name": "Tempero de Vinagre Tradicional Castelo Leve Vita 450ml",
  "category": "Vinagres",
  "price": 19.14,
  "listPrice": 19.14,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155705/Tempero-de-Vinagre-Tradicional.png?v=637644618426830000",
  "link": "tempero-vinagre-tradicional-450ml",
  "desc": "O Tempero de Vinagre Tradicional da linha Leve Vita é feito à base do vinagre de álcool com ervas, especiarias e pimenta",
  "recommended": false
 },
 {
  "id": "26",
  "name": "Creme de Balsâmico com Framboesa 230ml",
  "category": "Vinagres",
  "price": 19.8,
  "listPrice": 19.8,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156044/mk_balsamico_creme_framboesa_230ml.png?v=638451749662700000",
  "link": "creme-balsamico-framboesa-230ml",
  "desc": "Elaborado á partir da redução do vinagre balsâmico o Creme de Vinagre Balsâmico com framboesa  possui suco natural da fr",
  "recommended": false
 },
 {
  "id": "20",
  "name": "Vinagre Balsâmico Tradizionale Castelo 500ml",
  "category": "Vinagres",
  "price": 20.68,
  "listPrice": 20.68,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155455/balsamico500.jpg?v=637539033204300000",
  "link": "vinagre-balsamico-tradizionale-500ml",
  "desc": "Elaborado a partir de vinagre de vinho tinto e extratos vegetais de altíssima qualidade, sendo concebido com a mais avan",
  "recommended": false
 },
 {
  "id": "22",
  "name": "Vinagre Balsâmico com Maracujá Castelo Fruttati 250ml",
  "category": "Vinagres",
  "price": 20.8,
  "listPrice": 20.8,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155456/balsamicomaracuja.jpg?v=637539033210730000",
  "link": "vinagre-balsamico-maracuja-250ml",
  "desc": "O Vinagre Balsâmico com Maracujá Castelo Fruttati é adicionado de suco e ingredientes. Por sua característica agridoce, ",
  "recommended": false
 },
 {
  "id": "15",
  "name": "Vinagre de Maçã 100% Natural Castelo 500ml",
  "category": "Vinagres",
  "price": 21.72,
  "listPrice": 21.72,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155447/macanatural.jpg?v=637516768037300000",
  "link": "vinagre-maca-natural-500ml",
  "desc": "O Vinagre de Maçã 100% Natural Castelo Leve Vita não contém conservantes e nem corantes e possui inúmeros benefícios por",
  "recommended": false
 },
 {
  "id": "18",
  "name": "Vinagre de Maçã Orgânico Castelo Leve Vita 250ml",
  "category": "Vinagres",
  "price": 22.29,
  "listPrice": 22.29,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155449/macaorganico.jpg?v=637516768053400000",
  "link": "vinagre-maca-organico-250ml",
  "desc": "Obtido por meio da fermentação lenta e gradual do suco integral de mação orgânica. Sem adição de corantes, conservantes ",
  "recommended": false
 },
 {
  "id": "105",
  "name": "Vinagre Balsâmico Orgânico Castelo 250ml",
  "category": "Vinagres",
  "price": 22.48,
  "listPrice": 22.48,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155760/Vinagre-Balsamico-Organico.jpg?v=637739788138730000",
  "link": "vinagre-balsamico-organico-castelo-250ml",
  "desc": "O Vinagre Balsâmico é muito apreciado na gastronomia por seu aroma característico e baixa acidez.",
  "recommended": false
 },
 {
  "id": "92",
  "name": "Sachê Vinagre Vinho Tinto Castelo Cx 200un-4ml",
  "category": "Vinagres",
  "price": 22.77,
  "listPrice": 22.77,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155511/sachetbinho.jpg?v=637539134492670000",
  "link": "sache-vinagre-vinho-tinto-4ml",
  "desc": "Os sachês Castelo são perfeitos para garantir que o autêntico sabor do Vinagre de Vinho Tinto esteja presente nos mais v",
  "recommended": false
 },
 {
  "id": "33",
  "name": "Vinagre de Álcool 6% Castelo 5l",
  "category": "Vinagres",
  "price": 23.46,
  "listPrice": 23.46,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155509/alcool5lt.jpg?v=637539134482800000",
  "link": "vinagre-alcool-6-5l",
  "desc": "O Vinagre de Álcool 6% é 50% mais concentrado que o Vinagre de Álcool Tradicional. Possui 6% de acidez.",
  "recommended": false
 },
 {
  "id": "24",
  "name": "Vinagre Balsâmico com Azeite Extra Virgem Castelo Fruttati 250ml",
  "category": "Vinagres",
  "price": 25.55,
  "listPrice": 25.55,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155458/balsamicoazeite.jpg?v=637539033221670000",
  "link": "vinagre-balsamico-azeite-extra-virgem-250ml",
  "desc": "Vinagre Balsâmico com Azeite Extra-Virgem Castelo Fruttati é adicionado de azeite extra-virgem e ingredientes naturais",
  "recommended": false
 },
 {
  "id": "16",
  "name": "Vinagre de Maçã com Suco de Maçã e Mel 100% Natural Castelo 500 ml",
  "category": "Vinagres",
  "price": 26.7,
  "listPrice": 26.7,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155459/macamelnatural.jpg?v=637539033230900000",
  "link": "vinagre-maca-mel-natural-500ml",
  "desc": "É um vinagre não filtrado, não possui corantes, conservantes ou aromatizantes.\r\nContém suco de maçã, que possui potencia",
  "recommended": false
 },
 {
  "id": "17",
  "name": "Vinagre de Vinho Tinto com Suco de Uva 100% Natural Castelo 500ml",
  "category": "Vinagres",
  "price": 26.71,
  "listPrice": 26.71,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155448/vinhotintonatural.jpg?v=637516768046370000",
  "link": "vinagre-vinho-tinto-suco-uva-natural-500ml",
  "desc": "É um vinagre não filtrado, não possui corantes, conservantes ou aromatizantes. \r\nContém suco da uva, que promove mais di",
  "recommended": false
 },
 {
  "id": "109",
  "name": "Vinagre de Maçã Orgânico Castelo Leve Vita 500ml",
  "category": "Vinagres",
  "price": 28.98,
  "listPrice": 28.98,
  "available": true,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156174/mockup_vinagre_maca_organico_500ml.jpg?v=638939055615200000",
  "link": "vinagre-de-maca-organico-castelo-leve-vita-500ml",
  "desc": "Obtido por meio da fermentação lenta e gradual do suco integral de mação orgânica. Sem adição de corantes, conservantes ",
  "recommended": false
 },
 {
  "id": "78",
  "name": "Azeitonas Verdes com Caroço Stand Up Pouch Castelo 80g",
  "category": "Conservas",
  "price": 3.12,
  "listPrice": 3.12,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155466/azeitonaverdecomcaroco.jpg?v=637539051433200000",
  "link": "azeitonas-verdes-caroco-pouch-80g",
  "desc": "As azeitonas Castelo passam\u000bpor um rigoroso processo de qualidade antes de chegar na sua casa! Experimente inclui-las no",
  "recommended": false
 },
 {
  "id": "62",
  "name": "Alcaparras Castelo 100g",
  "category": "Conservas",
  "price": 13.6,
  "listPrice": 13.6,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155584/alcaparra..jpg?v=637575642283600000",
  "link": "alcaparras",
  "desc": "Alcaparras Castelo são perfeitas para adicionar toque especial aos seus pratos. Experimente Alcaparras Castelo e desfrut",
  "recommended": false
 },
 {
  "id": "74",
  "name": "Pimenta Biquinho Castelo 180g",
  "category": "Conservas",
  "price": 14.11,
  "listPrice": 14.11,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155488/pimentabiquinho.jpg?v=637539083253730000",
  "link": "pimenta-biquinho-180g",
  "desc": "A Pimenta Biquinho Castelo é adquirida de produtores que primam pela qualidade e passam por uma rigorosa seleção, sendo ",
  "recommended": false
 },
 {
  "id": "97",
  "name": "Kit Patês de Pimenta Biquinho",
  "category": "Kits",
  "price": 30.48,
  "listPrice": 30.48,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155669/kit-pates.png?v=637596343346130000",
  "link": "kit-pates-pimenta-biquinho",
  "desc": "Com os Patês de Pimenta Biquinho Sem Conservantes Castelo suas receitas apresentarão um toque a mais de criatividade, so",
  "recommended": false
 },
 {
  "id": "98",
  "name": "Kit Creme Balsâmico Tradicional e Framboesa Castelo",
  "category": "Kits",
  "price": 37.06,
  "listPrice": 37.06,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155684/kit-creme-balsamico.png?v=637600654259900000",
  "link": "kit-creme-balsamico-tradicional-e-framboesa-castelo",
  "desc": "O Creme Balsâmico Castelo é elaborado a partir da redução do Vinagre Balsâmico, conta com uma nova receita, com concentr",
  "recommended": false
 },
 {
  "id": "53",
  "name": "Molho de Pimenta Castelo 150ml",
  "category": "Molhos",
  "price": 2.52,
  "listPrice": 2.52,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155939/pimenta_150ml.png?v=638260644369100000",
  "link": "molho-pimenta-150ml",
  "desc": "O Molho de Pimenta Castelo é ideal para o preparo de inúmeros pratos à base de carne ou peixe.",
  "recommended": false
 },
 {
  "id": "42",
  "name": "Molho para Salada Italiano Castelo 236ml",
  "category": "Molhos",
  "price": 6.98,
  "listPrice": 6.98,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156118/mockup_molhos_italiano.png.png?v=638724738641930000",
  "link": "molho-para-salada-italiano-236ml",
  "desc": "O Molho para Salada Italiano é combinação perfeita de vinagrete, especiarias e queijo parmesão",
  "recommended": false
 },
 {
  "id": "91",
  "name": "Maionese Pote Castelo 500g",
  "category": "Molhos",
  "price": 7.41,
  "listPrice": 7.41,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155672/mk_maionese_pote_500g_2020.png?v=637598971600730000",
  "link": "maionese-pote-500g",
  "desc": "A Maionese Castelo faz toda a diferença na preparação de molhos, carne vermelha, frango ou peixe, patês, recheio de sand",
  "recommended": false
 },
 {
  "id": "59",
  "name": "Patê de Pimenta Biquinho Defumado Castelo 250g",
  "category": "Patês Pimenta",
  "price": 11.29,
  "listPrice": 11.29,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155589/pate_pimenta_defumado.jpg?v=637575705309630000",
  "link": "pate-pimenta-biquinho-defumado-250g",
  "desc": "O Patê de Pimenta Biquinho Defumado Sem Conservantes Castelo não possui picância. É feito com pimentas selecionadas, pro",
  "recommended": false
 },
 {
  "id": "31",
  "name": "Vinagre de Álcool  6% 2l Castelo",
  "category": "Vinagres",
  "price": 12.33,
  "listPrice": 12.33,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155508/alcool2lt.jpg?v=637539134473730000",
  "link": "vinagre-alcool-6-2l",
  "desc": "É perfeito para conservas e higienização de alimentos. O Vinagre de Álcool  6% é 50% mais concentrado que o Vinagre de Á",
  "recommended": false
 },
 {
  "id": "165",
  "name": "Kit Vinagre de Maçã Castelo com Vinagre de Álcool Castelo 750ml",
  "category": "Vinagres",
  "price": 16.11,
  "listPrice": 16.11,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156197/PACK-VINAGRE-DE-ALCOOL-VINAGRE-DE-MACA-750ML.png?v=639017516045230000",
  "link": "vinagre-de-maca-castelo-vinagre-de-alcool-castelo-750ml",
  "desc": "O Vinagre de Fruta Maçã Castelo é um produto 100% saudável, que ajuda no bom funcionamento do organismo.",
  "recommended": false
 },
 {
  "id": "23",
  "name": "Vinagre Balsâmico com Framboesa Castelo Fruttati 250ml",
  "category": "Vinagres",
  "price": 20.8,
  "listPrice": 20.8,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/155457/balsamicoframboesa.jpg?v=637539033216830000",
  "link": "vinagre-balsamico-framboesa-250ml",
  "desc": "O Vinagre Balsâmico com Framboesa Castelo Fruttati é adicionado de suco e ingredientes naturais. Por sua característica ",
  "recommended": false
 },
 {
  "id": "25",
  "name": "Creme de Balsâmico Tradicional Castelo 230ml",
  "category": "Vinagres",
  "price": 21.38,
  "listPrice": 21.38,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156041/mk_balsamico_creme_tradicional_230ml.png?v=638451746666270000",
  "link": "creme-balsamico-tradicional-230ml",
  "desc": "Elaborado a partir da redução do Vinagre Balsâmico, conta com uma nova receita, com concentração maior de suco de uva. O",
  "recommended": false
 },
 {
  "id": "166",
  "name": "Kit Vinagre de Fruta Maçã Sem Conservantes Castelo Leve Vita 400ml",
  "category": "Vinagres",
  "price": 21.66,
  "listPrice": 21.66,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156200/PACK-VINAGRES-SEM-CONSERVANTES-PET.png?v=639017614855030000",
  "link": "kit-vinagre-de-fruta-maca-sem-conservantes-castelo-leve-vita-400ml",
  "desc": "Descubra a nova versão do nosso clássico vinagre de maçã, agora em frasco PET de 400ml! O Vinagre de Fruta Maçã Sem Cons",
  "recommended": false
 },
 {
  "id": "164",
  "name": "Kit Vinagre de Álcool Aromatizado Citrus 6% e Vinagre de Álcool Aromatizado Maçã Verde 6%",
  "category": "Vinagres",
  "price": 26.92,
  "listPrice": 26.92,
  "available": false,
  "image": "https://t76496.vteximg.com.br/arquivos/ids/156195/PACK-VINAGRE-6-.png?v=639008175597030000",
  "link": "vinagre-de-alcool-aromatizado-citrus-6-vinagre-de-alcool-aromatizado-maca-verde-6-",
  "desc": "Vinagre de Álcool Aromatizado Citrus 6% e Vinagre de Álcool Aromatizado Maçã Verde 6% é a solução ecológica e de múltipl",
  "recommended": false
 }
];
